print("|-----------------|--------------|")
print("|   Expression    |   Result     | ")
print("|-----------------|--------------|")
print("| 2 * 3           |",int(2 * 3),end="            |\n" )
print("| 2 ** 3          |",int(2 ** 3),end="            |\n" )
print("| (5+2)*5         |",int((5+2))*5,end="           |\n" )
print("| (-4)-(-4)-(-4)  |",float(-4--4--4),end="          |\n" )
print("| 2 ** 2 ** 0     |",float(2 ** 2 ** 0),end="          |\n" )
print("| (2 ** 2) ** 0   |",float((2 ** 2) ** 0),end="          |\n" )
print("| 6 // 2          |",float(6 // 2),end="          |\n")
print("| 6.0 / 4.0       |",float(6 / 2),end="          |\n")
print("| 2.0 // 2.5      |",float(2.0 // 2.5),end="          |\n")
print("| 9.0 * 0.5       |",float(9.0 * 0.5),end="          |\n")
print("| 9.0 ** 0.5      |",float(9.0 ** 0.5),end="          |\n")
print("| 6 % 2           |",float(6 % 2),end="          |\n")
print("| 8 % 3           |",float(8 % 3),end="          |\n")
print("| 6.2 % 4         |",float(6.2 % 4),end="          |\n")
print("|-----------------|--------------|")
