print("|-----------------|--------------|")
print("|   Expression    |   Result     | ")
print("|-----------------|--------------|")
print("| 3 < 5           |",bool(3 < 5),end="         |\n" )
print("| 2 < 5 and 5 < 3 |",bool(2<5 and 5<3),end="        |\n" )
print("| True            |",bool(True),end="         |\n" )
print("| true            |",end="trueisdefine  |\n" )
print("| True and False  |",bool(True and False),end="        |\n" )
print("| True or False   |",bool(True or False),end="         |\n" )
print("| not True        |",bool(not True),end="        |\n")
print("| not not False   |",bool(not not False),end="        |\n")
print("| notFalseandTrue |",bool(not False and True),end="         |\n")
print("| not(FalseorTrue)|",bool(not(False and True)),end="         |\n")
print("| Truan(FlsandTue)|",bool(True and False and True),end="          |\n")
print("| Truor(FlsandTue)|",bool(True or (False and True)),end="          |\n")
print("| (5/0==1andFalse |",bool((5/0 == 1) and False),end="          |\n")
print("| Falseand(5/0==1)|",bool(False and (5/0==1)),end="          |\n")
print("|-----------------|--------------|")
