print("3<5:",bool(3<5))
print("3<5 and 5<3:",bool(3<5 and 5<3))
print("True:", bool(True))
print("true: NameError")
print("True and False:",bool(True and False))
print("True or False:",bool(True or False))
print("not True:",bool(not True))
print("not not False:",bool(not not False))
print("not False and True:",bool(not False and True))
print("not(False or True):",bool(not(False or True)))
print("True and False and True:",bool(True and False and True))
print("True or(False and True):",bool(True or(False and True)))
print("(5/0==1)and False:Divison by zero")
print("False and (5/0==1):Division by zero")
