print("float(4):",float(4))
print("int(5.3):",int(5.3))
print("int(True):",int(True))
print("float(int(5.3)):",float(int(5.3)))
print("int(5.7):",int(5.7))
print("float(7)//4:",float(7)//4)
print("int(7/4):",int(7/4))
print("6.2 and False:",float(6.2) and bool(0))
print("True and 6.2:",bool(True) and float(6.2))
print("type(4.5):",type(4.5))
print("type(True and 3):",type(True and 3))
